import type { Metadata } from 'next';
import { Oswald } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { ApolloWrapper } from '@/components/providers/ApolloWrapper';

const oswald = Oswald({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const SideNavigation = () => {
  return (
    <nav className="fixed flex justify-center h-full left-0 top-0 border-r-2 w-[75px]">
      <ul className="flex flex-col">
        <li>
          <Link href="/">Home</Link>
        </li>
        <li>
          <Link href="/tables">Tables</Link>
        </li>
        <li>
          <Link href="/messenger">Messenger</Link>
        </li>
      </ul>
    </nav>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={oswald.className + ' h-[100vh]'}>
        <ApolloWrapper>
          <SideNavigation />
          <main>
            {children}
          </main>
        </ApolloWrapper>
      </body>
    </html >
  );
}
